[package]
name = "clvm_rs"
version = "0.1.8"
authors = ["Richard Kiss <him@richardkiss.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clvm_rs"
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies.pyo3]
version = "0.14.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies]
clvm = { git = "https://github.com/Chia-Network/clvm_rs/", branch = "crate-only" }
