[package]
name = "clvm"
version = "0.1.8"
authors = ["Richard Kiss <him@richardkiss.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
hex = "0.4.2"
lazy_static = "1.4.0"
num-bigint = "0.3.1"
bls12_381 = "0.4.0"

[target.'cfg(windows)'.dependencies]
sha2 = "0.8.0"

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.32", features = ["vendored"] }
